# Generated by Django 3.1.7 on 2021-03-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20210316_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='sets',
            name='sets',
            field=models.IntegerField(null=True),
        ),
    ]
